version: '3.8'

services:
  newshub:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: newshub-production
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
      - SANITY_PROJECT_ID=247bx5rt
      - SANITY_DATASET=production
      - SANITY_API_VERSION=2024-01-01
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.newshub.rule=Host(\`your-domain.com\`)"
      - "traefik.http.routers.newshub.entrypoints=websecure"
      - "traefik.http.routers.newshub.tls.certresolver=letsencrypt"
      - "traefik.http.services.newshub.loadbalancer.server.port=80"
    networks:
      - web

networks:
  web:
    external: true